### PR TITLE
HIR-109 Added foreign keys to db and removed cascade delete, re-sorted methods in DbContext

### PR DESCRIPTION
**Pull request by AlexeyShok**
HIR-109 Added foreign keys to db and removed cascade delete, re-sorted methods in DbContext. Please see what other relationships between entities I need to add and write in the comments

### CODE REVIEW

**Review by oleg1std — CHANGES_REQUESTED** [review]
42704: constraint "FK_Accommodations_ContractManagers_ContractManagerId" of relation "Accommodations" does not exist

**Review by kirillta — APPROVED** [review]
OK, looks valid, may be approved once will work

**Review by mingazhev — APPROVED** [review]

**Comment by oleg1std** [comment]
Before a contract removing, one should remove entities from the tables: RoomRates, RoomPromotionalOffers, RoomAvailabilityRestrictions, RoomAllocationRequirements, PromotionalOffersStopSale, CancellationPolicies, SeasonRanges, Seasons, ContractAccommodationRelations

**Comment by oleg1std** [comment]
Please remove commented code from the migration file

**Review by oleg1std — APPROVED** [review]

**Pull request merged**
